// Bundled bridge: IMAP + SMTP MCP server bound to an app-specific
// password. Replaces the OAuth-mediated Google Workspace bridge for
// the secretary application after Google's lockdown of the gcloud
// ADC default OAuth client (May 2026).
//
// What this bridge ships:
//   - One MCP transport (ImapSmtpTransport) that speaks IMAP for
//     reads/writes/label-manipulation and SMTP for sends, both over
//     TLS.
//   - One synthetic endpoint key (mcp+imap://<host>/<email>) used by
//     mcp-attested's registry; the URL is not a real network address.
//   - A closed `allowedTools` list scoped to the implemented surface;
//     the admission gate denies anything not in this list before the
//     transport ever sees it.
//
// All five canonical tools (search_threads, get_thread, create_draft,
// send_draft, modify_thread_labels) are admitted as of PR3.
//
// Required env:
//   - ENCLAWED_IMAP_APP_PASSWORD — the 16-letter app-specific password
//     generated by the user at myaccount.google.com/apppasswords (or
//     equivalent on Fastmail/iCloud/Proton-via-Bridge/self-hosted).
//   - ENCLAWED_SECRETARY_PRINCIPAL_EMAIL — the IMAP/SMTP login
//     username, doubles as the From: address on outgoing messages.

import { registerServer, type RegisteredServer } from "../../mcp-attested/src/server-registry.js";
import { ImapSmtpTransport, type ImapSmtpTransportOptions } from "./imap-smtp-transport.js";

export { ImapSmtpTransport } from "./imap-smtp-transport.js";
export type {
  ImapSmtpTransportOptions,
  ThreadSummary,
  ThreadMessage,
  Address,
  CreateDraftInput,
  CreateDraftOutput,
  SendDraftInput,
  SendDraftOutput,
  ModifyThreadLabelsInput,
  ModifyThreadLabelsOutput,
} from "./imap-smtp-transport.js";

// Canonical tool list this bridge admits. Mirrors the Gmail-MCP-shape
// the secretary's runtime expects.
export const IMAP_SMTP_TOOLS = Object.freeze([
  "search_threads",
  "get_thread",
  "create_draft",
  "send_draft",
  "modify_thread_labels",
]);

export type ImapSmtpBridgeOptions = ImapSmtpTransportOptions & {
  /** Required clearance for the admission gate. Defaults to "internal". */
  requiredClearance?: string;
  /** Narrow the canonical tool list further (intersection only — never widens). */
  allowedToolsOverride?: ReadonlyArray<string>;
  /**
   * Override the synthetic endpoint key. By default it is
   * `mcp+imap://<imap.host>/<username>`. The runtime passes this same
   * string as McpToolCall.serverUrl when invoking the bridge.
   */
  endpoint?: string;
};

function syntheticEndpoint(opts: ImapSmtpBridgeOptions): string {
  if (opts.endpoint) {
    return opts.endpoint;
  }
  const u = encodeURIComponent(opts.username);
  return `mcp+imap://${opts.imap.host}/${u}`;
}

export function loadImapSmtpBridge(opts: ImapSmtpBridgeOptions): {
  registered: RegisteredServer;
} {
  const requiredClearance = opts.requiredClearance ?? "internal";
  const endpoint = syntheticEndpoint(opts);
  // Narrowing-only override (same security property as the Google
  // bridge): an unknown tool name in the override silently drops to
  // the canonical baseline rather than admitting through.
  const baseline = IMAP_SMTP_TOOLS;
  const allowedTools = opts.allowedToolsOverride
    ? Object.freeze(baseline.filter((t) => opts.allowedToolsOverride!.includes(t)))
    : baseline;
  const transport = new ImapSmtpTransport(opts);
  const entry: RegisteredServer = Object.freeze({
    id: "mcp.imap-smtp",
    bridge: "mcp-imap-smtp",
    endpoint,
    requiredClearance,
    allowedTools,
    transport,
  });
  registerServer(entry);
  return { registered: entry };
}
